# Generated by Django 2.0.6 on 2018-09-30 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0004_auto_20180930_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='autor',
        ),
        migrations.AddField(
            model_name='comments',
            name='autor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
