# Generated by Django 2.0.6 on 2018-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20181012_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='articuloOwn',
        ),
        migrations.AddField(
            model_name='comments',
            name='articuloOwn',
            field=models.ManyToManyField(blank=True, null=True, to='articulos.Articles'),
        ),
    ]
