# Generated by Django 2.0.6 on 2018-10-12 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0007_auto_20181012_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='autor',
        ),
        migrations.AddField(
            model_name='comments',
            name='autor',
            field=models.ForeignKey(blank=True, default=22, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
