# Generated by Django 2.0.6 on 2018-10-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_auto_20181012_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='articuloOwn',
        ),
        migrations.AddField(
            model_name='comments',
            name='articuloOwn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.Articles'),
        ),
    ]
