# Generated by Django 2.0.6 on 2018-10-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_auto_20181012_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articuloOwn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_comen', to='articulos.Articles'),
        ),
    ]
